services:
  haproxy:
    image: haproxy:3.3-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

  api1:
    image: ghcr.io/israelaraujo70/rinha-2026-asm:1b94df2
    platform: linux/amd64

    environment:
      SOCKET_PATH: /sockets/api1.sock
      IVF_NPROBE: "5"
      IVF_REPAIR_LIMIT: "1"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  api2:
    image: ghcr.io/israelaraujo70/rinha-2026-asm:1b94df2
    platform: linux/amd64

    environment:
      SOCKET_PATH: /sockets/api2.sock
      IVF_NPROBE: "5"
      IVF_REPAIR_LIMIT: "1"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

volumes:
  sockets:

